### ISSUE TITLE
Input/output test cases

### ISSUE THREAD

**Issue by gwroger** [Arpit1294/compiler-using-hackerrank-api#1]
I was wondering if you were implementing something to have test cases input/expected test cases output,
Thank you

**Comment by thebedroomprogrammer** [comment]
Yes, you can. Currently working on a react app for the compiler that has
this functionality will post it on blog as soon it's done.

**Comment by gwroger** [comment]
awesome, keep me posted I'm interested

**Comment by thebedroomprogrammer** [comment]
Yes, sure.

**Comment by gwroger** [comment]
I was wondering if you had a repo where you were pushing your work progress about that react project. I'm very interested and ready to help, let me know

**Comment by thebedroomprogrammer** [comment]
I am currently researching about it. Just got a full time job and my laptop
is sent for repair so currently I am not getting any time. As soon as I
start the project I would create a repo and send you the link.

**Comment by thebedroomprogrammer** [comment]
Closing the issue as hackerrank does not support the API now
