### ISSUE TITLE
Executing code locally

### ISSUE THREAD

**Issue by avijitatdirac** [Arpit1294/compiler-using-hackerrank-api#2]
I found your work on git hub and it can help us in creating a exam portal for our own use. I cloned your project and now I wanted to run it locally before hosting it on our server. But I have two questions:
1) what I should mention in package.json at the place where start: "node ./bin/www" is given. What is this? 
2) How do I start the server locally? Should I user "node app.js" ? 

Your answer can help a lot. Appreciate if you can revert.

**Comment by thebedroomprogrammer** [comment]
First of all thanks for considering the project. :)
I am afraid to tell you that hackerrank is discontinuing it's API support
so even though you clone the project you might not get it to work.

**Comment by avijitatdirac** [comment]
Thanks for reverting so quickly. I find your demo site hosted in heroku is still working just fine. So, hopefully hackerrank is still supporting the API. 

----------------------------------------

**Comment by thebedroomprogrammer** [comment]
Ok I will check it once again and revert to you shortly.

**Comment by thebedroomprogrammer** [comment]
The API won't work after 31st March please refer this.
https://www.hackerrank.com/api/docs

**Comment by thebedroomprogrammer** [comment]
Closing the issue as hackerrank does not support the API now
