### ISSUE TITLE
Can you add more languages 

### ISSUE THREAD

**Issue by isAlmogK** [Arpit1294/compiler-using-hackerrank-api#3]
Would you be interested in adding more languages as paid work?

**Comment by thebedroomprogrammer** [comment]
Hi Almog,
I have started this as a hobby project.
I am working on a similar game but using phaser 3. Once it gets complete
and running and I see if it has traffic then would surely love to add more
language support.

**Comment by isAlmogK** [comment]
Cool, if you do please let me know

**Comment by thebedroomprogrammer** [comment]
Yes Sure. I will let you know once I get it done.

**Comment by thebedroomprogrammer** [comment]
Closing the issue as hackerrank does not support the API now
